// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dstore/elastic/elasticservice.proto

package io.dstore.elastic;

public final class Elasticservice {
  private Elasticservice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#dstore/elastic/elasticservice.proto\022\016d" +
      "store.elastic\032+dstore/elastic/item/facet" +
      "ednavigation.proto\032!dstore/elastic/item/" +
      "suggest.proto2\324\001\n\016ElasticService\022n\n\021face" +
      "tedNavigation\022).dstore.elastic.facetedna" +
      "vigation.Request\032*.dstore.elastic.facete" +
      "dnavigation.Response\"\0000\001\022R\n\013itemSuggest\022" +
      "\037.dstore.elastic.suggest.Request\032 .dstor" +
      "e.elastic.suggest.Response\"\000B\023\n\021io.dstor" +
      "e.elasticb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.dstore.elastic.item.FacetedNavigation.getDescriptor(),
          io.dstore.elastic.item.Suggest.getDescriptor(),
        }, assigner);
    io.dstore.elastic.item.FacetedNavigation.getDescriptor();
    io.dstore.elastic.item.Suggest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
