// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dstore/elastic/elastic_service.proto

package io.dstore.elastic;

public final class ElasticServiceOuterClass {
  private ElasticServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$dstore/elastic/elastic_service.proto\022\016" +
      "dstore.elastic\032\"dstore/elastic/item/item" +
      "_get.proto\032&dstore/elastic/item/item_sug" +
      "gest.proto\032%dstore/elastic/item/item_exp" +
      "ort.proto2\317\001\n\007Elastic\022\\\n\007itemGet\022%.dstor" +
      "e.elastic.item.item_get.Request\032&.dstore" +
      ".elastic.item.item_get.Response\"\0000\001\022f\n\013i" +
      "temSuggest\022).dstore.elastic.item.item_su" +
      "ggest.Request\032*.dstore.elastic.item.item" +
      "_suggest.Response\"\000BV\n\021io.dstore.elastic",
      "B\030ElasticServiceOuterClassZ\'gosdk.dstore" +
      ".de/elastic/elastic_serviceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.dstore.elastic.item.ItemGet.getDescriptor(),
          io.dstore.elastic.item.ItemSuggest.getDescriptor(),
          io.dstore.elastic.item.ItemExport.getDescriptor(),
        }, assigner);
    io.dstore.elastic.item.ItemGet.getDescriptor();
    io.dstore.elastic.item.ItemSuggest.getDescriptor();
    io.dstore.elastic.item.ItemExport.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
