// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dstore/elastic/elastic.proto

package io.dstore.elastic;

public interface SortOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dstore.elastic.Sort)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .dstore.elastic.Sort.FieldSort field_sort = 1;</code>
   */
  io.dstore.elastic.Sort.FieldSort getFieldSort();
  /**
   * <code>optional .dstore.elastic.Sort.FieldSort field_sort = 1;</code>
   */
  io.dstore.elastic.Sort.FieldSortOrBuilder getFieldSortOrBuilder();

  /**
   * <code>optional .dstore.elastic.Sort.ScoreSort score_sort = 2;</code>
   */
  io.dstore.elastic.Sort.ScoreSort getScoreSort();
  /**
   * <code>optional .dstore.elastic.Sort.ScoreSort score_sort = 2;</code>
   */
  io.dstore.elastic.Sort.ScoreSortOrBuilder getScoreSortOrBuilder();

  public io.dstore.elastic.Sort.SortByCase getSortByCase();
}
