// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dstore/engine/engine.proto

package io.dstore.engine;

/**
 * Protobuf type {@code dstore.engine.MetaInformation}
 */
public  final class MetaInformation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dstore.engine.MetaInformation)
    MetaInformationOrBuilder {
  // Use MetaInformation.newBuilder() to construct.
  private MetaInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetaInformation() {
    type_ = 0;
    information_ = "";
    details_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MetaInformation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            information_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            details_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.dstore.engine.EngineOuterClass.internal_static_dstore_engine_MetaInformation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.dstore.engine.EngineOuterClass.internal_static_dstore_engine_MetaInformation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.dstore.engine.MetaInformation.class, io.dstore.engine.MetaInformation.Builder.class);
  }

  /**
   * Protobuf enum {@code dstore.engine.MetaInformation.Types}
   */
  public enum Types
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKOWN = 0;</code>
     */
    UNKOWN(0),
    /**
     * <code>SQL_STRING = 1;</code>
     */
    SQL_STRING(1),
    /**
     * <code>EXEC_TIME = 2;</code>
     */
    EXEC_TIME(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKOWN = 0;</code>
     */
    public static final int UNKOWN_VALUE = 0;
    /**
     * <code>SQL_STRING = 1;</code>
     */
    public static final int SQL_STRING_VALUE = 1;
    /**
     * <code>EXEC_TIME = 2;</code>
     */
    public static final int EXEC_TIME_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Types valueOf(int value) {
      return forNumber(value);
    }

    public static Types forNumber(int value) {
      switch (value) {
        case 0: return UNKOWN;
        case 1: return SQL_STRING;
        case 2: return EXEC_TIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Types>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Types> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Types>() {
            public Types findValueByNumber(int number) {
              return Types.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.dstore.engine.MetaInformation.getDescriptor().getEnumTypes().get(0);
    }

    private static final Types[] VALUES = values();

    public static Types valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Types(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dstore.engine.MetaInformation.Types)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
   */
  public io.dstore.engine.MetaInformation.Types getType() {
    io.dstore.engine.MetaInformation.Types result = io.dstore.engine.MetaInformation.Types.valueOf(type_);
    return result == null ? io.dstore.engine.MetaInformation.Types.UNRECOGNIZED : result;
  }

  public static final int INFORMATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object information_;
  /**
   * <code>optional string information = 2;</code>
   */
  public java.lang.String getInformation() {
    java.lang.Object ref = information_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      information_ = s;
      return s;
    }
  }
  /**
   * <code>optional string information = 2;</code>
   */
  public com.google.protobuf.ByteString
      getInformationBytes() {
    java.lang.Object ref = information_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      information_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAILS_FIELD_NUMBER = 3;
  private volatile java.lang.Object details_;
  /**
   * <code>optional string details = 3;</code>
   */
  public java.lang.String getDetails() {
    java.lang.Object ref = details_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      details_ = s;
      return s;
    }
  }
  /**
   * <code>optional string details = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDetailsBytes() {
    java.lang.Object ref = details_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      details_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != io.dstore.engine.MetaInformation.Types.UNKOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!getInformationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, information_);
    }
    if (!getDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, details_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != io.dstore.engine.MetaInformation.Types.UNKOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!getInformationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, information_);
    }
    if (!getDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, details_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.dstore.engine.MetaInformation)) {
      return super.equals(obj);
    }
    io.dstore.engine.MetaInformation other = (io.dstore.engine.MetaInformation) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && getInformation()
        .equals(other.getInformation());
    result = result && getDetails()
        .equals(other.getDetails());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + INFORMATION_FIELD_NUMBER;
    hash = (53 * hash) + getInformation().hashCode();
    hash = (37 * hash) + DETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getDetails().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.dstore.engine.MetaInformation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dstore.engine.MetaInformation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dstore.engine.MetaInformation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dstore.engine.MetaInformation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dstore.engine.MetaInformation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.dstore.engine.MetaInformation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.dstore.engine.MetaInformation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.dstore.engine.MetaInformation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.dstore.engine.MetaInformation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.dstore.engine.MetaInformation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.dstore.engine.MetaInformation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dstore.engine.MetaInformation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dstore.engine.MetaInformation)
      io.dstore.engine.MetaInformationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dstore.engine.EngineOuterClass.internal_static_dstore_engine_MetaInformation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dstore.engine.EngineOuterClass.internal_static_dstore_engine_MetaInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dstore.engine.MetaInformation.class, io.dstore.engine.MetaInformation.Builder.class);
    }

    // Construct using io.dstore.engine.MetaInformation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      information_ = "";

      details_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.dstore.engine.EngineOuterClass.internal_static_dstore_engine_MetaInformation_descriptor;
    }

    public io.dstore.engine.MetaInformation getDefaultInstanceForType() {
      return io.dstore.engine.MetaInformation.getDefaultInstance();
    }

    public io.dstore.engine.MetaInformation build() {
      io.dstore.engine.MetaInformation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.dstore.engine.MetaInformation buildPartial() {
      io.dstore.engine.MetaInformation result = new io.dstore.engine.MetaInformation(this);
      result.type_ = type_;
      result.information_ = information_;
      result.details_ = details_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.dstore.engine.MetaInformation) {
        return mergeFrom((io.dstore.engine.MetaInformation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.dstore.engine.MetaInformation other) {
      if (other == io.dstore.engine.MetaInformation.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getInformation().isEmpty()) {
        information_ = other.information_;
        onChanged();
      }
      if (!other.getDetails().isEmpty()) {
        details_ = other.details_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.dstore.engine.MetaInformation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.dstore.engine.MetaInformation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
     */
    public io.dstore.engine.MetaInformation.Types getType() {
      io.dstore.engine.MetaInformation.Types result = io.dstore.engine.MetaInformation.Types.valueOf(type_);
      return result == null ? io.dstore.engine.MetaInformation.Types.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
     */
    public Builder setType(io.dstore.engine.MetaInformation.Types value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .dstore.engine.MetaInformation.Types type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object information_ = "";
    /**
     * <code>optional string information = 2;</code>
     */
    public java.lang.String getInformation() {
      java.lang.Object ref = information_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        information_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string information = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInformationBytes() {
      java.lang.Object ref = information_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        information_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string information = 2;</code>
     */
    public Builder setInformation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      information_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string information = 2;</code>
     */
    public Builder clearInformation() {
      
      information_ = getDefaultInstance().getInformation();
      onChanged();
      return this;
    }
    /**
     * <code>optional string information = 2;</code>
     */
    public Builder setInformationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      information_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object details_ = "";
    /**
     * <code>optional string details = 3;</code>
     */
    public java.lang.String getDetails() {
      java.lang.Object ref = details_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        details_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string details = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDetailsBytes() {
      java.lang.Object ref = details_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        details_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string details = 3;</code>
     */
    public Builder setDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      details_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string details = 3;</code>
     */
    public Builder clearDetails() {
      
      details_ = getDefaultInstance().getDetails();
      onChanged();
      return this;
    }
    /**
     * <code>optional string details = 3;</code>
     */
    public Builder setDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      details_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:dstore.engine.MetaInformation)
  }

  // @@protoc_insertion_point(class_scope:dstore.engine.MetaInformation)
  private static final io.dstore.engine.MetaInformation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.dstore.engine.MetaInformation();
  }

  public static io.dstore.engine.MetaInformation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetaInformation>
      PARSER = new com.google.protobuf.AbstractParser<MetaInformation>() {
    public MetaInformation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetaInformation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetaInformation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetaInformation> getParserForType() {
    return PARSER;
  }

  public io.dstore.engine.MetaInformation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

