// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dstore/elastic/item/item.proto

package io.dstore.elastic.item;

/**
 * Protobuf type {@code dstore.elastic.item.item.Item}
 */
public  final class Item extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dstore.elastic.item.item.Item)
    ItemOrBuilder {
  // Use Item.newBuilder() to construct.
  private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Item() {
    variantNode_ = java.util.Collections.emptyList();
    score_ = 0D;
    indexName_ = "";
    documentId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Item(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.dstore.elastic.item.Item.Node.Builder subBuilder = null;
            if (node_ != null) {
              subBuilder = node_.toBuilder();
            }
            node_ = input.readMessage(io.dstore.elastic.item.Item.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(node_);
              node_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              variantNode_ = new java.util.ArrayList<io.dstore.elastic.item.Item.Node>();
              mutable_bitField0_ |= 0x00000002;
            }
            variantNode_.add(
                input.readMessage(io.dstore.elastic.item.Item.Node.parser(), extensionRegistry));
            break;
          }
          case 26: {
            io.dstore.values.TimestampValue.Builder subBuilder = null;
            if (lastUpdated_ != null) {
              subBuilder = lastUpdated_.toBuilder();
            }
            lastUpdated_ = input.readMessage(io.dstore.values.TimestampValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastUpdated_);
              lastUpdated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 81: {

            score_ = input.readDouble();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            indexName_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            documentId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        variantNode_ = java.util.Collections.unmodifiableList(variantNode_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.dstore.elastic.item.Item.class, io.dstore.elastic.item.Item.Builder.class);
  }

  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dstore.elastic.item.item.Item.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional int32 tree_node_id = 2;</code>
     */
    int getTreeNodeId();

    /**
     * <code>optional bool active = 3;</code>
     */
    boolean getActive();

    /**
     * <code>optional int32 level_id = 4;</code>
     */
    int getLevelId();

    /**
     * <code>optional int32 sort_no = 5;</code>
     */
    int getSortNo();

    /**
     * <code>repeated int32 predecessor_tree_node_id = 6;</code>
     */
    java.util.List<java.lang.Integer> getPredecessorTreeNodeIdList();
    /**
     * <code>repeated int32 predecessor_tree_node_id = 6;</code>
     */
    int getPredecessorTreeNodeIdCount();
    /**
     * <code>repeated int32 predecessor_tree_node_id = 6;</code>
     */
    int getPredecessorTreeNodeId(int index);

    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */
    int getFieldsCount();
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */
    boolean containsFields(
        java.lang.String key);
    /**
     * Use {@link #getFieldsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, io.dstore.elastic.Field>
    getFields();
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */
    java.util.Map<java.lang.String, io.dstore.elastic.Field>
    getFieldsMap();
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */

    io.dstore.elastic.Field getFieldsOrDefault(
        java.lang.String key,
        io.dstore.elastic.Field defaultValue);
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */

    io.dstore.elastic.Field getFieldsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code dstore.elastic.item.item.Item.Node}
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dstore.elastic.item.item.Item.Node)
      NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      description_ = "";
      treeNodeId_ = 0;
      active_ = false;
      levelId_ = 0;
      sortNo_ = 0;
      predecessorTreeNodeId_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 16: {

              treeNodeId_ = input.readInt32();
              break;
            }
            case 24: {

              active_ = input.readBool();
              break;
            }
            case 32: {

              levelId_ = input.readInt32();
              break;
            }
            case 40: {

              sortNo_ = input.readInt32();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                predecessorTreeNodeId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              predecessorTreeNodeId_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                predecessorTreeNodeId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                predecessorTreeNodeId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 162: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                fields_ = com.google.protobuf.MapField.newMapField(
                    FieldsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, io.dstore.elastic.Field>
              fields = input.readMessage(
                  FieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              fields_.getMutableMap().put(fields.getKey(), fields.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          predecessorTreeNodeId_ = java.util.Collections.unmodifiableList(predecessorTreeNodeId_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_Node_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 20:
          return internalGetFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dstore.elastic.item.Item.Node.class, io.dstore.elastic.item.Item.Node.Builder.class);
    }

    private int bitField0_;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>optional string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TREE_NODE_ID_FIELD_NUMBER = 2;
    private int treeNodeId_;
    /**
     * <code>optional int32 tree_node_id = 2;</code>
     */
    public int getTreeNodeId() {
      return treeNodeId_;
    }

    public static final int ACTIVE_FIELD_NUMBER = 3;
    private boolean active_;
    /**
     * <code>optional bool active = 3;</code>
     */
    public boolean getActive() {
      return active_;
    }

    public static final int LEVEL_ID_FIELD_NUMBER = 4;
    private int levelId_;
    /**
     * <code>optional int32 level_id = 4;</code>
     */
    public int getLevelId() {
      return levelId_;
    }

    public static final int SORT_NO_FIELD_NUMBER = 5;
    private int sortNo_;
    /**
     * <code>optional int32 sort_no = 5;</code>
     */
    public int getSortNo() {
      return sortNo_;
    }

    public static final int PREDECESSOR_TREE_NODE_ID_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> predecessorTreeNodeId_;
    /**
     * <code>repeated int32 predecessor_tree_node_id = 6;</code>
     */
    public java.util.List<java.lang.Integer>
        getPredecessorTreeNodeIdList() {
      return predecessorTreeNodeId_;
    }
    /**
     * <code>repeated int32 predecessor_tree_node_id = 6;</code>
     */
    public int getPredecessorTreeNodeIdCount() {
      return predecessorTreeNodeId_.size();
    }
    /**
     * <code>repeated int32 predecessor_tree_node_id = 6;</code>
     */
    public int getPredecessorTreeNodeId(int index) {
      return predecessorTreeNodeId_.get(index);
    }
    private int predecessorTreeNodeIdMemoizedSerializedSize = -1;

    public static final int FIELDS_FIELD_NUMBER = 20;
    private static final class FieldsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, io.dstore.elastic.Field> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, io.dstore.elastic.Field>newDefaultInstance(
                  io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_Node_FieldsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  io.dstore.elastic.Field.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, io.dstore.elastic.Field> fields_;
    private com.google.protobuf.MapField<java.lang.String, io.dstore.elastic.Field>
    internalGetFields() {
      if (fields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FieldsDefaultEntryHolder.defaultEntry);
      }
      return fields_;
    }

    public int getFieldsCount() {
      return internalGetFields().getMap().size();
    }
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */

    public boolean containsFields(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFields().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFieldsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.dstore.elastic.Field> getFields() {
      return getFieldsMap();
    }
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */

    public java.util.Map<java.lang.String, io.dstore.elastic.Field> getFieldsMap() {
      return internalGetFields().getMap();
    }
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */

    public io.dstore.elastic.Field getFieldsOrDefault(
        java.lang.String key,
        io.dstore.elastic.Field defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.dstore.elastic.Field> map =
          internalGetFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
     */

    public io.dstore.elastic.Field getFieldsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.dstore.elastic.Field> map =
          internalGetFields().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, description_);
      }
      if (treeNodeId_ != 0) {
        output.writeInt32(2, treeNodeId_);
      }
      if (active_ != false) {
        output.writeBool(3, active_);
      }
      if (levelId_ != 0) {
        output.writeInt32(4, levelId_);
      }
      if (sortNo_ != 0) {
        output.writeInt32(5, sortNo_);
      }
      if (getPredecessorTreeNodeIdList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(predecessorTreeNodeIdMemoizedSerializedSize);
      }
      for (int i = 0; i < predecessorTreeNodeId_.size(); i++) {
        output.writeInt32NoTag(predecessorTreeNodeId_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, io.dstore.elastic.Field> entry
           : internalGetFields().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, io.dstore.elastic.Field>
        fields = FieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(20, fields);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, description_);
      }
      if (treeNodeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, treeNodeId_);
      }
      if (active_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, active_);
      }
      if (levelId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, levelId_);
      }
      if (sortNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sortNo_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < predecessorTreeNodeId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(predecessorTreeNodeId_.get(i));
        }
        size += dataSize;
        if (!getPredecessorTreeNodeIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        predecessorTreeNodeIdMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.String, io.dstore.elastic.Field> entry
           : internalGetFields().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, io.dstore.elastic.Field>
        fields = FieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(20, fields);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dstore.elastic.item.Item.Node)) {
        return super.equals(obj);
      }
      io.dstore.elastic.item.Item.Node other = (io.dstore.elastic.item.Item.Node) obj;

      boolean result = true;
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (getTreeNodeId()
          == other.getTreeNodeId());
      result = result && (getActive()
          == other.getActive());
      result = result && (getLevelId()
          == other.getLevelId());
      result = result && (getSortNo()
          == other.getSortNo());
      result = result && getPredecessorTreeNodeIdList()
          .equals(other.getPredecessorTreeNodeIdList());
      result = result && internalGetFields().equals(
          other.internalGetFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + TREE_NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTreeNodeId();
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getActive());
      hash = (37 * hash) + LEVEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLevelId();
      hash = (37 * hash) + SORT_NO_FIELD_NUMBER;
      hash = (53 * hash) + getSortNo();
      if (getPredecessorTreeNodeIdCount() > 0) {
        hash = (37 * hash) + PREDECESSOR_TREE_NODE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPredecessorTreeNodeIdList().hashCode();
      }
      if (!internalGetFields().getMap().isEmpty()) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFields().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dstore.elastic.item.Item.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dstore.elastic.item.Item.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dstore.elastic.item.Item.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dstore.elastic.item.Item.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dstore.elastic.item.Item.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dstore.elastic.item.item.Item.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dstore.elastic.item.item.Item.Node)
        io.dstore.elastic.item.Item.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_Node_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 20:
            return internalGetFields();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 20:
            return internalGetMutableFields();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dstore.elastic.item.Item.Node.class, io.dstore.elastic.item.Item.Node.Builder.class);
      }

      // Construct using io.dstore.elastic.item.Item.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        description_ = "";

        treeNodeId_ = 0;

        active_ = false;

        levelId_ = 0;

        sortNo_ = 0;

        predecessorTreeNodeId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        internalGetMutableFields().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_Node_descriptor;
      }

      public io.dstore.elastic.item.Item.Node getDefaultInstanceForType() {
        return io.dstore.elastic.item.Item.Node.getDefaultInstance();
      }

      public io.dstore.elastic.item.Item.Node build() {
        io.dstore.elastic.item.Item.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.dstore.elastic.item.Item.Node buildPartial() {
        io.dstore.elastic.item.Item.Node result = new io.dstore.elastic.item.Item.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.description_ = description_;
        result.treeNodeId_ = treeNodeId_;
        result.active_ = active_;
        result.levelId_ = levelId_;
        result.sortNo_ = sortNo_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          predecessorTreeNodeId_ = java.util.Collections.unmodifiableList(predecessorTreeNodeId_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.predecessorTreeNodeId_ = predecessorTreeNodeId_;
        result.fields_ = internalGetFields();
        result.fields_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dstore.elastic.item.Item.Node) {
          return mergeFrom((io.dstore.elastic.item.Item.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dstore.elastic.item.Item.Node other) {
        if (other == io.dstore.elastic.item.Item.Node.getDefaultInstance()) return this;
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getTreeNodeId() != 0) {
          setTreeNodeId(other.getTreeNodeId());
        }
        if (other.getActive() != false) {
          setActive(other.getActive());
        }
        if (other.getLevelId() != 0) {
          setLevelId(other.getLevelId());
        }
        if (other.getSortNo() != 0) {
          setSortNo(other.getSortNo());
        }
        if (!other.predecessorTreeNodeId_.isEmpty()) {
          if (predecessorTreeNodeId_.isEmpty()) {
            predecessorTreeNodeId_ = other.predecessorTreeNodeId_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePredecessorTreeNodeIdIsMutable();
            predecessorTreeNodeId_.addAll(other.predecessorTreeNodeId_);
          }
          onChanged();
        }
        internalGetMutableFields().mergeFrom(
            other.internalGetFields());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dstore.elastic.item.Item.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dstore.elastic.item.Item.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 1;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int treeNodeId_ ;
      /**
       * <code>optional int32 tree_node_id = 2;</code>
       */
      public int getTreeNodeId() {
        return treeNodeId_;
      }
      /**
       * <code>optional int32 tree_node_id = 2;</code>
       */
      public Builder setTreeNodeId(int value) {
        
        treeNodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tree_node_id = 2;</code>
       */
      public Builder clearTreeNodeId() {
        
        treeNodeId_ = 0;
        onChanged();
        return this;
      }

      private boolean active_ ;
      /**
       * <code>optional bool active = 3;</code>
       */
      public boolean getActive() {
        return active_;
      }
      /**
       * <code>optional bool active = 3;</code>
       */
      public Builder setActive(boolean value) {
        
        active_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool active = 3;</code>
       */
      public Builder clearActive() {
        
        active_ = false;
        onChanged();
        return this;
      }

      private int levelId_ ;
      /**
       * <code>optional int32 level_id = 4;</code>
       */
      public int getLevelId() {
        return levelId_;
      }
      /**
       * <code>optional int32 level_id = 4;</code>
       */
      public Builder setLevelId(int value) {
        
        levelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level_id = 4;</code>
       */
      public Builder clearLevelId() {
        
        levelId_ = 0;
        onChanged();
        return this;
      }

      private int sortNo_ ;
      /**
       * <code>optional int32 sort_no = 5;</code>
       */
      public int getSortNo() {
        return sortNo_;
      }
      /**
       * <code>optional int32 sort_no = 5;</code>
       */
      public Builder setSortNo(int value) {
        
        sortNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sort_no = 5;</code>
       */
      public Builder clearSortNo() {
        
        sortNo_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> predecessorTreeNodeId_ = java.util.Collections.emptyList();
      private void ensurePredecessorTreeNodeIdIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          predecessorTreeNodeId_ = new java.util.ArrayList<java.lang.Integer>(predecessorTreeNodeId_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public java.util.List<java.lang.Integer>
          getPredecessorTreeNodeIdList() {
        return java.util.Collections.unmodifiableList(predecessorTreeNodeId_);
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public int getPredecessorTreeNodeIdCount() {
        return predecessorTreeNodeId_.size();
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public int getPredecessorTreeNodeId(int index) {
        return predecessorTreeNodeId_.get(index);
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public Builder setPredecessorTreeNodeId(
          int index, int value) {
        ensurePredecessorTreeNodeIdIsMutable();
        predecessorTreeNodeId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public Builder addPredecessorTreeNodeId(int value) {
        ensurePredecessorTreeNodeIdIsMutable();
        predecessorTreeNodeId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public Builder addAllPredecessorTreeNodeId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePredecessorTreeNodeIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, predecessorTreeNodeId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 predecessor_tree_node_id = 6;</code>
       */
      public Builder clearPredecessorTreeNodeId() {
        predecessorTreeNodeId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, io.dstore.elastic.Field> fields_;
      private com.google.protobuf.MapField<java.lang.String, io.dstore.elastic.Field>
      internalGetFields() {
        if (fields_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FieldsDefaultEntryHolder.defaultEntry);
        }
        return fields_;
      }
      private com.google.protobuf.MapField<java.lang.String, io.dstore.elastic.Field>
      internalGetMutableFields() {
        onChanged();;
        if (fields_ == null) {
          fields_ = com.google.protobuf.MapField.newMapField(
              FieldsDefaultEntryHolder.defaultEntry);
        }
        if (!fields_.isMutable()) {
          fields_ = fields_.copy();
        }
        return fields_;
      }

      public int getFieldsCount() {
        return internalGetFields().getMap().size();
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */

      public boolean containsFields(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetFields().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFieldsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.dstore.elastic.Field> getFields() {
        return getFieldsMap();
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */

      public java.util.Map<java.lang.String, io.dstore.elastic.Field> getFieldsMap() {
        return internalGetFields().getMap();
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */

      public io.dstore.elastic.Field getFieldsOrDefault(
          java.lang.String key,
          io.dstore.elastic.Field defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.dstore.elastic.Field> map =
            internalGetFields().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */

      public io.dstore.elastic.Field getFieldsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.dstore.elastic.Field> map =
            internalGetFields().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearFields() {
        getMutableFields().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */

      public Builder removeFields(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableFields().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.dstore.elastic.Field>
      getMutableFields() {
        return internalGetMutableFields().getMutableMap();
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */
      public Builder putFields(
          java.lang.String key,
          io.dstore.elastic.Field value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableFields().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .dstore.elastic.Field&gt; fields = 20;</code>
       */

      public Builder putAllFields(
          java.util.Map<java.lang.String, io.dstore.elastic.Field> values) {
        getMutableFields().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dstore.elastic.item.item.Item.Node)
    }

    // @@protoc_insertion_point(class_scope:dstore.elastic.item.item.Item.Node)
    private static final io.dstore.elastic.item.Item.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dstore.elastic.item.Item.Node();
    }

    public static io.dstore.elastic.item.Item.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    public io.dstore.elastic.item.Item.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int NODE_FIELD_NUMBER = 1;
  private io.dstore.elastic.item.Item.Node node_;
  /**
   * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
   */
  public boolean hasNode() {
    return node_ != null;
  }
  /**
   * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
   */
  public io.dstore.elastic.item.Item.Node getNode() {
    return node_ == null ? io.dstore.elastic.item.Item.Node.getDefaultInstance() : node_;
  }
  /**
   * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
   */
  public io.dstore.elastic.item.Item.NodeOrBuilder getNodeOrBuilder() {
    return getNode();
  }

  public static final int VARIANT_NODE_FIELD_NUMBER = 2;
  private java.util.List<io.dstore.elastic.item.Item.Node> variantNode_;
  /**
   * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
   */
  public java.util.List<io.dstore.elastic.item.Item.Node> getVariantNodeList() {
    return variantNode_;
  }
  /**
   * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
   */
  public java.util.List<? extends io.dstore.elastic.item.Item.NodeOrBuilder> 
      getVariantNodeOrBuilderList() {
    return variantNode_;
  }
  /**
   * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
   */
  public int getVariantNodeCount() {
    return variantNode_.size();
  }
  /**
   * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
   */
  public io.dstore.elastic.item.Item.Node getVariantNode(int index) {
    return variantNode_.get(index);
  }
  /**
   * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
   */
  public io.dstore.elastic.item.Item.NodeOrBuilder getVariantNodeOrBuilder(
      int index) {
    return variantNode_.get(index);
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 3;
  private io.dstore.values.TimestampValue lastUpdated_;
  /**
   * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
   */
  public boolean hasLastUpdated() {
    return lastUpdated_ != null;
  }
  /**
   * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
   */
  public io.dstore.values.TimestampValue getLastUpdated() {
    return lastUpdated_ == null ? io.dstore.values.TimestampValue.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
   */
  public io.dstore.values.TimestampValueOrBuilder getLastUpdatedOrBuilder() {
    return getLastUpdated();
  }

  public static final int SCORE_FIELD_NUMBER = 10;
  private double score_;
  /**
   * <code>optional double score = 10;</code>
   */
  public double getScore() {
    return score_;
  }

  public static final int INDEX_NAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object indexName_;
  /**
   * <code>optional string index_name = 11;</code>
   */
  public java.lang.String getIndexName() {
    java.lang.Object ref = indexName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      indexName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string index_name = 11;</code>
   */
  public com.google.protobuf.ByteString
      getIndexNameBytes() {
    java.lang.Object ref = indexName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      indexName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOCUMENT_ID_FIELD_NUMBER = 12;
  private volatile java.lang.Object documentId_;
  /**
   * <code>optional string document_id = 12;</code>
   */
  public java.lang.String getDocumentId() {
    java.lang.Object ref = documentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      documentId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string document_id = 12;</code>
   */
  public com.google.protobuf.ByteString
      getDocumentIdBytes() {
    java.lang.Object ref = documentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      documentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (node_ != null) {
      output.writeMessage(1, getNode());
    }
    for (int i = 0; i < variantNode_.size(); i++) {
      output.writeMessage(2, variantNode_.get(i));
    }
    if (lastUpdated_ != null) {
      output.writeMessage(3, getLastUpdated());
    }
    if (score_ != 0D) {
      output.writeDouble(10, score_);
    }
    if (!getIndexNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, indexName_);
    }
    if (!getDocumentIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, documentId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (node_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNode());
    }
    for (int i = 0; i < variantNode_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, variantNode_.get(i));
    }
    if (lastUpdated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLastUpdated());
    }
    if (score_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, score_);
    }
    if (!getIndexNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, indexName_);
    }
    if (!getDocumentIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, documentId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.dstore.elastic.item.Item)) {
      return super.equals(obj);
    }
    io.dstore.elastic.item.Item other = (io.dstore.elastic.item.Item) obj;

    boolean result = true;
    result = result && (hasNode() == other.hasNode());
    if (hasNode()) {
      result = result && getNode()
          .equals(other.getNode());
    }
    result = result && getVariantNodeList()
        .equals(other.getVariantNodeList());
    result = result && (hasLastUpdated() == other.hasLastUpdated());
    if (hasLastUpdated()) {
      result = result && getLastUpdated()
          .equals(other.getLastUpdated());
    }
    result = result && (
        java.lang.Double.doubleToLongBits(getScore())
        == java.lang.Double.doubleToLongBits(
            other.getScore()));
    result = result && getIndexName()
        .equals(other.getIndexName());
    result = result && getDocumentId()
        .equals(other.getDocumentId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasNode()) {
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode().hashCode();
    }
    if (getVariantNodeCount() > 0) {
      hash = (37 * hash) + VARIANT_NODE_FIELD_NUMBER;
      hash = (53 * hash) + getVariantNodeList().hashCode();
    }
    if (hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getScore()));
    hash = (37 * hash) + INDEX_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getIndexName().hashCode();
    hash = (37 * hash) + DOCUMENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDocumentId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.dstore.elastic.item.Item parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dstore.elastic.item.Item parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dstore.elastic.item.Item parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.dstore.elastic.item.Item parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.dstore.elastic.item.Item parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.dstore.elastic.item.Item parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.dstore.elastic.item.Item parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.dstore.elastic.item.Item parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.dstore.elastic.item.Item parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.dstore.elastic.item.Item parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.dstore.elastic.item.Item prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dstore.elastic.item.item.Item}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dstore.elastic.item.item.Item)
      io.dstore.elastic.item.ItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dstore.elastic.item.Item.class, io.dstore.elastic.item.Item.Builder.class);
    }

    // Construct using io.dstore.elastic.item.Item.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVariantNodeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (nodeBuilder_ == null) {
        node_ = null;
      } else {
        node_ = null;
        nodeBuilder_ = null;
      }
      if (variantNodeBuilder_ == null) {
        variantNode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        variantNodeBuilder_.clear();
      }
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }
      score_ = 0D;

      indexName_ = "";

      documentId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.dstore.elastic.item.ItemOuterClass.internal_static_dstore_elastic_item_item_Item_descriptor;
    }

    public io.dstore.elastic.item.Item getDefaultInstanceForType() {
      return io.dstore.elastic.item.Item.getDefaultInstance();
    }

    public io.dstore.elastic.item.Item build() {
      io.dstore.elastic.item.Item result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.dstore.elastic.item.Item buildPartial() {
      io.dstore.elastic.item.Item result = new io.dstore.elastic.item.Item(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (nodeBuilder_ == null) {
        result.node_ = node_;
      } else {
        result.node_ = nodeBuilder_.build();
      }
      if (variantNodeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          variantNode_ = java.util.Collections.unmodifiableList(variantNode_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.variantNode_ = variantNode_;
      } else {
        result.variantNode_ = variantNodeBuilder_.build();
      }
      if (lastUpdatedBuilder_ == null) {
        result.lastUpdated_ = lastUpdated_;
      } else {
        result.lastUpdated_ = lastUpdatedBuilder_.build();
      }
      result.score_ = score_;
      result.indexName_ = indexName_;
      result.documentId_ = documentId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.dstore.elastic.item.Item) {
        return mergeFrom((io.dstore.elastic.item.Item)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.dstore.elastic.item.Item other) {
      if (other == io.dstore.elastic.item.Item.getDefaultInstance()) return this;
      if (other.hasNode()) {
        mergeNode(other.getNode());
      }
      if (variantNodeBuilder_ == null) {
        if (!other.variantNode_.isEmpty()) {
          if (variantNode_.isEmpty()) {
            variantNode_ = other.variantNode_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureVariantNodeIsMutable();
            variantNode_.addAll(other.variantNode_);
          }
          onChanged();
        }
      } else {
        if (!other.variantNode_.isEmpty()) {
          if (variantNodeBuilder_.isEmpty()) {
            variantNodeBuilder_.dispose();
            variantNodeBuilder_ = null;
            variantNode_ = other.variantNode_;
            bitField0_ = (bitField0_ & ~0x00000002);
            variantNodeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariantNodeFieldBuilder() : null;
          } else {
            variantNodeBuilder_.addAllMessages(other.variantNode_);
          }
        }
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      if (other.getScore() != 0D) {
        setScore(other.getScore());
      }
      if (!other.getIndexName().isEmpty()) {
        indexName_ = other.indexName_;
        onChanged();
      }
      if (!other.getDocumentId().isEmpty()) {
        documentId_ = other.documentId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.dstore.elastic.item.Item parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.dstore.elastic.item.Item) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.dstore.elastic.item.Item.Node node_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dstore.elastic.item.Item.Node, io.dstore.elastic.item.Item.Node.Builder, io.dstore.elastic.item.Item.NodeOrBuilder> nodeBuilder_;
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public boolean hasNode() {
      return nodeBuilder_ != null || node_ != null;
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public io.dstore.elastic.item.Item.Node getNode() {
      if (nodeBuilder_ == null) {
        return node_ == null ? io.dstore.elastic.item.Item.Node.getDefaultInstance() : node_;
      } else {
        return nodeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public Builder setNode(io.dstore.elastic.item.Item.Node value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        node_ = value;
        onChanged();
      } else {
        nodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public Builder setNode(
        io.dstore.elastic.item.Item.Node.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        node_ = builderForValue.build();
        onChanged();
      } else {
        nodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public Builder mergeNode(io.dstore.elastic.item.Item.Node value) {
      if (nodeBuilder_ == null) {
        if (node_ != null) {
          node_ =
            io.dstore.elastic.item.Item.Node.newBuilder(node_).mergeFrom(value).buildPartial();
        } else {
          node_ = value;
        }
        onChanged();
      } else {
        nodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public Builder clearNode() {
      if (nodeBuilder_ == null) {
        node_ = null;
        onChanged();
      } else {
        node_ = null;
        nodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public io.dstore.elastic.item.Item.Node.Builder getNodeBuilder() {
      
      onChanged();
      return getNodeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    public io.dstore.elastic.item.Item.NodeOrBuilder getNodeOrBuilder() {
      if (nodeBuilder_ != null) {
        return nodeBuilder_.getMessageOrBuilder();
      } else {
        return node_ == null ?
            io.dstore.elastic.item.Item.Node.getDefaultInstance() : node_;
      }
    }
    /**
     * <code>optional .dstore.elastic.item.item.Item.Node node = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dstore.elastic.item.Item.Node, io.dstore.elastic.item.Item.Node.Builder, io.dstore.elastic.item.Item.NodeOrBuilder> 
        getNodeFieldBuilder() {
      if (nodeBuilder_ == null) {
        nodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.dstore.elastic.item.Item.Node, io.dstore.elastic.item.Item.Node.Builder, io.dstore.elastic.item.Item.NodeOrBuilder>(
                getNode(),
                getParentForChildren(),
                isClean());
        node_ = null;
      }
      return nodeBuilder_;
    }

    private java.util.List<io.dstore.elastic.item.Item.Node> variantNode_ =
      java.util.Collections.emptyList();
    private void ensureVariantNodeIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        variantNode_ = new java.util.ArrayList<io.dstore.elastic.item.Item.Node>(variantNode_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.dstore.elastic.item.Item.Node, io.dstore.elastic.item.Item.Node.Builder, io.dstore.elastic.item.Item.NodeOrBuilder> variantNodeBuilder_;

    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public java.util.List<io.dstore.elastic.item.Item.Node> getVariantNodeList() {
      if (variantNodeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variantNode_);
      } else {
        return variantNodeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public int getVariantNodeCount() {
      if (variantNodeBuilder_ == null) {
        return variantNode_.size();
      } else {
        return variantNodeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public io.dstore.elastic.item.Item.Node getVariantNode(int index) {
      if (variantNodeBuilder_ == null) {
        return variantNode_.get(index);
      } else {
        return variantNodeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder setVariantNode(
        int index, io.dstore.elastic.item.Item.Node value) {
      if (variantNodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantNodeIsMutable();
        variantNode_.set(index, value);
        onChanged();
      } else {
        variantNodeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder setVariantNode(
        int index, io.dstore.elastic.item.Item.Node.Builder builderForValue) {
      if (variantNodeBuilder_ == null) {
        ensureVariantNodeIsMutable();
        variantNode_.set(index, builderForValue.build());
        onChanged();
      } else {
        variantNodeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder addVariantNode(io.dstore.elastic.item.Item.Node value) {
      if (variantNodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantNodeIsMutable();
        variantNode_.add(value);
        onChanged();
      } else {
        variantNodeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder addVariantNode(
        int index, io.dstore.elastic.item.Item.Node value) {
      if (variantNodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantNodeIsMutable();
        variantNode_.add(index, value);
        onChanged();
      } else {
        variantNodeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder addVariantNode(
        io.dstore.elastic.item.Item.Node.Builder builderForValue) {
      if (variantNodeBuilder_ == null) {
        ensureVariantNodeIsMutable();
        variantNode_.add(builderForValue.build());
        onChanged();
      } else {
        variantNodeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder addVariantNode(
        int index, io.dstore.elastic.item.Item.Node.Builder builderForValue) {
      if (variantNodeBuilder_ == null) {
        ensureVariantNodeIsMutable();
        variantNode_.add(index, builderForValue.build());
        onChanged();
      } else {
        variantNodeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder addAllVariantNode(
        java.lang.Iterable<? extends io.dstore.elastic.item.Item.Node> values) {
      if (variantNodeBuilder_ == null) {
        ensureVariantNodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variantNode_);
        onChanged();
      } else {
        variantNodeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder clearVariantNode() {
      if (variantNodeBuilder_ == null) {
        variantNode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        variantNodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public Builder removeVariantNode(int index) {
      if (variantNodeBuilder_ == null) {
        ensureVariantNodeIsMutable();
        variantNode_.remove(index);
        onChanged();
      } else {
        variantNodeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public io.dstore.elastic.item.Item.Node.Builder getVariantNodeBuilder(
        int index) {
      return getVariantNodeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public io.dstore.elastic.item.Item.NodeOrBuilder getVariantNodeOrBuilder(
        int index) {
      if (variantNodeBuilder_ == null) {
        return variantNode_.get(index);  } else {
        return variantNodeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public java.util.List<? extends io.dstore.elastic.item.Item.NodeOrBuilder> 
         getVariantNodeOrBuilderList() {
      if (variantNodeBuilder_ != null) {
        return variantNodeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variantNode_);
      }
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public io.dstore.elastic.item.Item.Node.Builder addVariantNodeBuilder() {
      return getVariantNodeFieldBuilder().addBuilder(
          io.dstore.elastic.item.Item.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public io.dstore.elastic.item.Item.Node.Builder addVariantNodeBuilder(
        int index) {
      return getVariantNodeFieldBuilder().addBuilder(
          index, io.dstore.elastic.item.Item.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .dstore.elastic.item.item.Item.Node variant_node = 2;</code>
     */
    public java.util.List<io.dstore.elastic.item.Item.Node.Builder> 
         getVariantNodeBuilderList() {
      return getVariantNodeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.dstore.elastic.item.Item.Node, io.dstore.elastic.item.Item.Node.Builder, io.dstore.elastic.item.Item.NodeOrBuilder> 
        getVariantNodeFieldBuilder() {
      if (variantNodeBuilder_ == null) {
        variantNodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.dstore.elastic.item.Item.Node, io.dstore.elastic.item.Item.Node.Builder, io.dstore.elastic.item.Item.NodeOrBuilder>(
                variantNode_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        variantNode_ = null;
      }
      return variantNodeBuilder_;
    }

    private io.dstore.values.TimestampValue lastUpdated_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dstore.values.TimestampValue, io.dstore.values.TimestampValue.Builder, io.dstore.values.TimestampValueOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public boolean hasLastUpdated() {
      return lastUpdatedBuilder_ != null || lastUpdated_ != null;
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public io.dstore.values.TimestampValue getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? io.dstore.values.TimestampValue.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public Builder setLastUpdated(io.dstore.values.TimestampValue value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public Builder setLastUpdated(
        io.dstore.values.TimestampValue.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public Builder mergeLastUpdated(io.dstore.values.TimestampValue value) {
      if (lastUpdatedBuilder_ == null) {
        if (lastUpdated_ != null) {
          lastUpdated_ =
            io.dstore.values.TimestampValue.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
        } else {
          lastUpdated_ = value;
        }
        onChanged();
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public Builder clearLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
        onChanged();
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public io.dstore.values.TimestampValue.Builder getLastUpdatedBuilder() {
      
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    public io.dstore.values.TimestampValueOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            io.dstore.values.TimestampValue.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>optional .dstore.values.TimestampValue last_updated = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.dstore.values.TimestampValue, io.dstore.values.TimestampValue.Builder, io.dstore.values.TimestampValueOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.dstore.values.TimestampValue, io.dstore.values.TimestampValue.Builder, io.dstore.values.TimestampValueOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }

    private double score_ ;
    /**
     * <code>optional double score = 10;</code>
     */
    public double getScore() {
      return score_;
    }
    /**
     * <code>optional double score = 10;</code>
     */
    public Builder setScore(double value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double score = 10;</code>
     */
    public Builder clearScore() {
      
      score_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object indexName_ = "";
    /**
     * <code>optional string index_name = 11;</code>
     */
    public java.lang.String getIndexName() {
      java.lang.Object ref = indexName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        indexName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string index_name = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIndexNameBytes() {
      java.lang.Object ref = indexName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indexName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string index_name = 11;</code>
     */
    public Builder setIndexName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      indexName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string index_name = 11;</code>
     */
    public Builder clearIndexName() {
      
      indexName_ = getDefaultInstance().getIndexName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string index_name = 11;</code>
     */
    public Builder setIndexNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      indexName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object documentId_ = "";
    /**
     * <code>optional string document_id = 12;</code>
     */
    public java.lang.String getDocumentId() {
      java.lang.Object ref = documentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        documentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string document_id = 12;</code>
     */
    public com.google.protobuf.ByteString
        getDocumentIdBytes() {
      java.lang.Object ref = documentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        documentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string document_id = 12;</code>
     */
    public Builder setDocumentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      documentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string document_id = 12;</code>
     */
    public Builder clearDocumentId() {
      
      documentId_ = getDefaultInstance().getDocumentId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string document_id = 12;</code>
     */
    public Builder setDocumentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      documentId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:dstore.elastic.item.item.Item)
  }

  // @@protoc_insertion_point(class_scope:dstore.elastic.item.item.Item)
  private static final io.dstore.elastic.item.Item DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.dstore.elastic.item.Item();
  }

  public static io.dstore.elastic.item.Item getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Item>
      PARSER = new com.google.protobuf.AbstractParser<Item>() {
    public Item parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Item> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Item> getParserForType() {
    return PARSER;
  }

  public io.dstore.elastic.item.Item getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

